### ISSUE TITLE
import libraries aren't created (MSVC15)

### ISSUE THREAD

**Issue by sgeto** [winlibs/libiconv#3] opened 2017-06-10 20:31 UTC
First of all:
Thanks for this. You've saved me (and many others I'm sure) a lot of time and headache.

I just have a quick question:
I've noticed that no import libraries (iconv*.lib) are produced when building the DLL.
Is this by design?
I only tried the VC2015 solution as this is the only IDE I use.

If not, I could help you make the solutions produce import libraries as well.
Also, it would be cool if you could bump up the platform toolchain for the VC2015 solution as well.
And a visual studio project file for the application (iconv.exe) would be nice as well. 😄 

Again, I can help out with these (requests) if needed.

Thanks again and have a nice day

**Comment by weltling** [comment] 2017-06-10 22:09
@sgeto thanks for checking this repo out in first place. I'm not sure, what goes wrong on your side in first place. This org is dedicated to produce deps for PHP, and there vc14 builds are actually in place for some time already http://windows.php.net/downloads/php-sdk/deps/vc14/ . It could be, that some change were forgotten to be synced into git, i'd have to check it. Or, that you expect a bit different naming scheme. With `iconv.exe' project - yeah, please give a PR if you're interested. Whereby i have to say, nowadays only vc14/vc15 is the only relevant target, older solutions should likely be removed.

Thanks.

**Comment by sgeto** [comment] 2017-06-10 22:13
oh I just noticed that the import libraries are for some reason placed in a diffent directory that the all other output files:
libiconv\MSVC15\Release/Debug
instead of 
libiconv\MSVC15\libiconv_dll\Debug
is that by design?

**Comment by weltling** [comment] 2017-06-10 22:31
Certainly not by design :) These solutions are made by hand quite long ago, as the original lib doesn't provide any way to build on Windows. Fine to fix as OFC, I might get to it if you didn't earlier. If you go for both lib location and iconv.exe, please lets do it in separate PRs.

Thanks.

**Comment by sgeto** [comment] 2017-06-11 05:44
:+1:

**Comment by weltling** [comment] 2018-01-12 12:00
PR merged.

Thanks.

**Closed as completed by weltling** 2018-01-12 12:00 UTC
